# Generated by Django 5.2.4 on 2025-10-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_panel', '0002_attendance_check_in_attendance_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='embedding',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
