# Generated by Django 5.2.4 on 2025-09-02 07:39

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('start_datetime', models.DateTimeField(verbose_name='Inicio')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('is_private', models.BooleanField(default=False, verbose_name='¿Privado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('business_name', models.CharField(max_length=200, verbose_name='Nombre comercial')),
                ('state', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CONTACTING', 'Contacting'), ('INTERESTED', 'Interested'), ('QUOTING', 'Quoting'), ('CLOSED', 'Closed'), ('INACTIVE', 'Inactive'), ('NOT_VIABLE', 'Not Viable')], default='PROSPECT', max_length=20, verbose_name='Estado del lead')),
                ('geographic_zone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zona geográfica')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Requerimientos')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.CharField(max_length=200, verbose_name='Categoría')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('position', models.CharField(max_length=100, verbose_name='Puesto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('event_type', models.CharField(choices=[('CALL', 'Llamada'), ('VISIT', 'Visita'), ('EMAIL', 'Correo'), ('MEETING', 'Reunión')], max_length=20, verbose_name='Tipo de evento')),
                ('start_time', models.DateTimeField(verbose_name='Hora de inicio')),
                ('end_time', models.DateTimeField(verbose_name='Hora de fin')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('external_calendar_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID en calendario externo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del gasto')),
                ('expense_type', models.CharField(choices=[('GAS', 'Gasolina'), ('TOLLS', 'Casetas'), ('OTHER', 'Otros')], max_length=50, verbose_name='Tipo de gasto')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='Comprobante')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadIndustry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('industry', models.CharField(max_length=200, verbose_name='Industria')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('client', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cliente')),
                ('origin', models.CharField(blank=True, max_length=150, null=True, verbose_name='Origen')),
                ('destiny', models.CharField(blank=True, max_length=150, null=True, verbose_name='Destino')),
                ('tipo_carga', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de carga')),
                ('unit', models.CharField(blank=True, max_length=150, null=True, verbose_name='Unidad')),
                ('requerimientos', models.CharField(blank=True, max_length=150, null=True, verbose_name='Requerimientos')),
                ('peso', models.CharField(blank=True, max_length=150, null=True, verbose_name='Peso (Kgs)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Costo')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2025, 9, 2, 1, 39, 30, 643987), null=True, verbose_name='Fecha de operacion')),
                ('cost1', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Costo')),
                ('cost2', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Costo')),
                ('cost3', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Costo')),
                ('cost4', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Costo')),
                ('cost5', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Costo')),
                ('comment1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentarios')),
                ('comment2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentarios')),
                ('comment3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentarios')),
                ('comment4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentarios')),
                ('comment5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentarios')),
                ('status_de_cotizacion', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('EN_ESPERA', 'EN_ESPERA'), ('EMITIDA', 'EMITIDA'), ('ACEPTADA', 'ACEPTADA'), ('CANCELADA', 'CANCELADA')], default='EN_ESPERA', max_length=30, null=True, verbose_name='Status de cotizacion')),
                ('importancia_de_cotizacion', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('LOW', 'BAJA'), ('MED', 'MEDIA'), ('HIGH', 'ALTA')], default='HIGH', max_length=30, null=True, verbose_name='Importancia')),
                ('client_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email del cliente')),
                ('email_sended', models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Se envio el correo?')),
                ('docx', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='telegram_images/')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Cotizacion de viaje',
                'verbose_name_plural': 'Cotizaciones de viajes',
                'db_table': 'travel_quote',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_completed', models.BooleanField(default=False, verbose_name='¿Completada?')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='¿Recurrente?')),
                ('recurrence_interval', models.DurationField(blank=True, null=True, verbose_name='Intervalo de recurrencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
