# Generated by Django 5.2.4 on 2025-09-02 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations_panel', '0001_initial'),
        ('sales_panel', '0001_initial'),
        ('telegram_bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='telegram_bots.telegramuser', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='operations_panel.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='telegram_bots.telegramuser', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_lead', to='sales_panel.leadcategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='lead_contacts', to='sales_panel.leadcontact', verbose_name='Contactos'),
        ),
        migrations.AddField(
            model_name='leadevent',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sales_panel.lead', verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='leadexpense',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sales_panel.lead', verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_type_lead', to='sales_panel.leadindustry', verbose_name='Industria'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='final_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_supplier', to='operations_panel.supplier', verbose_name='Proveedor seleccionado'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier1', to='operations_panel.supplier', verbose_name='Proveedor #1'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier2', to='operations_panel.supplier', verbose_name='Proveedor #2'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier3', to='operations_panel.supplier', verbose_name='Proveedor #3'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier4', to='operations_panel.supplier', verbose_name='Proveedor #4'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier5', to='operations_panel.supplier', verbose_name='Proveedor #5'),
        ),
    ]
