# Generated by Django 5.2.4 on 2025-09-02 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 2, 3, 17, 48, 97533), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
