# Generated by Django 5.2.4 on 2025-09-02 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0004_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 2, 5, 49, 40, 198398), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
