# Generated by Django 5.2.4 on 2025-09-02 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0008_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 2, 7, 33, 44, 164694), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
