# Generated by Django 5.2.4 on 2025-10-24 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0015_lead_old_id_leadcategory_old_id_leadcontact_old_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 10, 24, 15, 16, 29, 430353), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
