# Generated by Django 5.2.4 on 2025-10-24 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0016_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 10, 24, 15, 55, 53, 224941), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
