# Generated by Django 5.2.4 on 2025-10-26 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0017_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 10, 26, 3, 27, 46, 114145), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
