# Generated by Django 5.2.4 on 2026-02-10 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0018_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 2, 10, 3, 38, 4, 908458), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
