# Generated by Django 5.2.4 on 2026-03-24 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0023_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 24, 1, 48, 28, 341321), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
