# Generated by Django 5.2.4 on 2026-04-30 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0028_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 4, 30, 10, 40, 2, 447644), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
