# Generated by Django 5.2.4 on 2026-05-11 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0029_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 5, 11, 4, 34, 39, 472854), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
