# Generated by Django 5.2.4 on 2026-05-27 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0030_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 5, 27, 1, 11, 39, 751968), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
