# Generated by Django 5.2.4 on 2026-06-02 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0033_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 2, 9, 43, 28, 402498), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
