# Generated by Django 5.2.4 on 2026-06-09 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0034_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 9, 1, 54, 8, 660061), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
