# Generated by Django 5.2.4 on 2026-06-16 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0035_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 6, 16, 12, 22, 18, 353743), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
