# Generated by Django 5.2.4 on 2026-07-22 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0037_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 7, 22, 11, 57, 3, 653698), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
