# Generated by Django 5.2.4 on 2026-07-22 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0038_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 7, 22, 15, 56, 25, 113923), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
