# Generated by Django 5.2.4 on 2026-10-05 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_panel', '0040_alter_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 10, 5, 8, 8, 39, 70008), null=True, verbose_name='Fecha de operacion'),
        ),
    ]
