# Generated by Django 5.2.4 on 2025-09-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturapi', '0001_initial'),
        ('operations_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturapi.facturapiinvoice'),
        ),
    ]
