# Generated by Django 5.2.4 on 2025-09-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturapi', '0001_initial'),
        ('operations_panel', '0002_operation_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='invoice',
        ),
        migrations.CreateModel(
            name='ShipmentFacturapiInvoice',
            fields=[
                ('facturapiinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturapi.facturapiinvoice')),
                ('total_distance_km', models.PositiveIntegerField(default=0, verbose_name='Distancia total a recorrer (km)')),
                ('departure_at', models.DateTimeField(verbose_name='Fecha y hora de salida')),
                ('scheduled_arrival_at', models.DateTimeField(verbose_name='Fecha y hora programada de llegada')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Nombre del remitente')),
                ('sender_rfc', models.CharField(max_length=13, verbose_name='RFC del remitente')),
                ('sct_permit_number', models.CharField(max_length=100, verbose_name='Número de permiso SCT')),
                ('insurer_name', models.CharField(max_length=100, verbose_name='Nombre de la aseguradora')),
                ('insurance_policy_number', models.CharField(max_length=100, verbose_name='Número de póliza de seguro')),
                ('sct_permit_type', models.CharField(max_length=100, verbose_name='Tipo de permiso SCT')),
                ('ccp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Carta Porte (ccp_id)')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations_panel.operation')),
            ],
            options={
                'verbose_name': 'Cartaporte',
                'verbose_name_plural': 'Cartaportes',
            },
            bases=('facturapi.facturapiinvoice',),
        ),
    ]
