# Generated by Django 5.2.4 on 2025-09-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturapi', '0001_initial'),
        ('operations_panel', '0003_remove_operation_invoice_shipmentfacturapiinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='facturapi.facturapiinvoice'),
        ),
        migrations.AddField(
            model_name='operation',
            name='shipment_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_invoice', to='facturapi.facturapiinvoice'),
        ),
    ]
