# Generated by Django 5.2.4 on 2025-09-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0004_operation_invoices_operation_shipment_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='deliveries',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='origin',
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('', 'Seleccion el estado'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Coahuila  de Zaragoza', 'Coahuila de Zaragoza'), ('Colima', 'Colima'), ('Ciudad de México', 'Ciudad de México'), ('Cdmx', 'Cdmx'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Mexico', 'Mexico'), ('Michoacan de Ocampo', 'Michoacan de Ocampo'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo Leon', 'Nuevo Leon'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Queretaro de Arteaga', 'Queretaro de Arteaga'), ('Quintana', 'Quintana Roo'), ('San Luis Potosi', 'San Luis Potosi'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatan', 'Yucatan'), ('Zacatecas', 'Zacatecas')], default='Queretaro de Arteaga', max_length=50, verbose_name='Estado'),
        ),
    ]
