# Generated by Django 5.2.4 on 2025-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0005_remove_operation_deliveries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicada'),
        ),
    ]
