# Generated by Django 5.2.4 on 2025-09-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0006_route_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='client',
        ),
    ]
