# Generated by Django 5.2.4 on 2025-10-23 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0007_remove_route_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTransportedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('weight', models.FloatField(verbose_name='Peso en Kg')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transported_products_operation', to='operations_panel.operation', verbose_name='Operación')),
                ('transported_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations_panel.transportedproduct', verbose_name='Producto base')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
