# Generated by Django 5.2.4 on 2025-10-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0009_address_old_id_cargo_old_id_client_old_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('TORTHON', 'TORTHON'), ('TRACTO', 'TRACTO'), ('CAJA', 'CAJA'), ('UNIDAD 1 TN', 'UNIDAD 1 TN'), ('UNIDAD 2.5 TN', 'UNIDAD 2.5 TN'), ('UNIDAD 3.5 TN', 'UNIDAD 3.5 TN'), ('UNIDAD 5 TN', 'UNIDAD 5 TN'), ('RABON', 'RABON'), ('CAJA 40’', 'CAJA 40’'), ('CAJA 48’', 'CAJA 48’'), ('CAJA 53’', 'CAJA 53’'), ('PLATAFORMA 40’', 'PLATAFORMA 40’'), ('PLATAFORMA 48’', 'PLATAFORMA 48’'), ('PIPA', 'PIPA'), ('TOLVA', 'TOLVA'), ('MADRINA', 'MADRINA'), ('VEHICULO UTILITARIO', 'VEHICULO UTILITARIO'), ('SIN ESPECIFICAR', 'SIN ESPECIFICAR')], max_length=30, null=True, verbose_name='Tipo de unidad'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='unit_type',
            field=models.CharField(choices=[('TORTHON', 'TORTHON'), ('TRACTO', 'TRACTO'), ('CAJA', 'CAJA'), ('UNIDAD 1 TN', 'UNIDAD 1 TN'), ('UNIDAD 2.5 TN', 'UNIDAD 2.5 TN'), ('UNIDAD 3.5 TN', 'UNIDAD 3.5 TN'), ('UNIDAD 5 TN', 'UNIDAD 5 TN'), ('RABON', 'RABON'), ('CAJA 40’', 'CAJA 40’'), ('CAJA 48’', 'CAJA 48’'), ('CAJA 53’', 'CAJA 53’'), ('PLATAFORMA 40’', 'PLATAFORMA 40’'), ('PLATAFORMA 48’', 'PLATAFORMA 48’'), ('PIPA', 'PIPA'), ('TOLVA', 'TOLVA'), ('MADRINA', 'MADRINA'), ('VEHICULO UTILITARIO', 'VEHICULO UTILITARIO'), ('SIN ESPECIFICAR', 'SIN ESPECIFICAR')], max_length=30, verbose_name='Tipo de unidad'),
        ),
    ]
