# Generated by Django 5.2.4 on 2026-03-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0010_alter_operation_vehicle_type_alter_vehicle_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_config',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE: PENDIENTE'), ('VL', 'VL: Light cargo vehicle'), ('C2', 'C2: Unit truck (2 front wheels, 4 rear wheels)'), ('C3', 'C3: Unit truck (2 front wheels, 6–8 rear wheels)'), ('C2R2', 'C2R2: Truck-Trailer (6 truck wheels, 8 trailer wheels)'), ('C3R2', 'C3R2: Truck-Trailer (10 truck wheels, 8 trailer wheels)'), ('C2R3', 'C2R3: Truck-Trailer (6 truck wheels, 12 trailer wheels)'), ('C3R3', 'C3R3: Truck-Trailer (10 truck wheels, 12 trailer wheels)'), ('T2S1', 'T2S1: Articulated tractor (6+4)'), ('T2S2', 'T2S2: Articulated tractor (6+8)'), ('T2S3', 'T2S3: Articulated tractor (6+12)'), ('T3S1', 'T3S1: Articulated tractor (10+4)'), ('T3S2', 'T3S2: Articulated tractor (10+8)'), ('T3S3', 'T3S3: Articulated tractor (10+12)'), ('T2S1R2', 'T2S1R2: Tractor-Semitrailer-Trailer (6+4+8)'), ('T2S2R2', 'T2S2R2: Tractor-Semitrailer-Trailer (6+8+8)'), ('T2S1R3', 'T2S1R3: Tractor-Semitrailer-Trailer (6+4+12)'), ('T3S1R2', 'T3S1R2: Tractor-Semitrailer-Trailer (10+4+8)'), ('T3S1R3', 'T3S1R3: Tractor-Semitrailer-Trailer (10+4+12)'), ('T3S2R2', 'T3S2R2: Tractor-Semitrailer-Trailer (10+8+8)'), ('T3S2R3', 'T3S2R3: Tractor-Semitrailer-Trailer (10+8+12)'), ('T3S2R4', 'T3S2R4: Tractor-Semitrailer-Trailer (10+8+16)'), ('T2S2S2', 'T2S2S2: Tractor-Semitrailer-Semitrailer (6+8+8)'), ('T3S2S2', 'T3S2S2: Tractor-Semitrailer-Semitrailer (10+8+8)'), ('T3S3S2', 'T3S3S2: Tractor-Semitrailer-Semitrailer (10+12+8)'), ('OTROEV', 'OTROEV: Voluminous specialized'), ('OTROEGP', 'OTROEGP: Heavy load specialized'), ('OTROSG', 'OTROSG: Crane service'), ('CTR001', 'CTR001: Caballete'), ('CTR002', 'CTR002: Box'), ('CTR003', 'CTR003: Open Box'), ('CTR004', 'CTR004: Closed Box'), ('CTR005', 'CTR005: Front Loader Collection Box'), ('CTR006', 'CTR006: Refrigerated Box'), ('CTR007', 'CTR007: Dry Box'), ('CTR008', 'CTR008: Transfer Box'), ('CTR009', 'CTR009: Low Bed'), ('CTR010', 'CTR010: Container Chassis'), ('CTR011', 'CTR011: Conventional Chassis'), ('CTR012', 'CTR012: Special Equipment'), ('CTR013', 'CTR013: Stakes'), ('CTR014', 'CTR014: Madrina Gondola'), ('CTR015', 'CTR015: Industrial Crane'), ('CTR016', 'CTR016: Crane'), ('CTR017', 'CTR017: Integral'), ('CTR018', 'CTR018: Cage'), ('CTR019', 'CTR019: Half Rails'), ('CTR020', 'CTR020: Pallet or Cells'), ('CTR021', 'CTR021: Platform'), ('CTR022', 'CTR022: Platform with Crane'), ('CTR023', 'CTR023: Curtain-sided Platform'), ('CTR024', 'CTR024: Rails'), ('CTR025', 'CTR025: Refrigerator'), ('CTR026', 'CTR026: Mixer'), ('CTR027', 'CTR027: Half Box'), ('CTR028', 'CTR028: Tank'), ('CTR029', 'CTR029: Hopper'), ('CTR030', 'CTR030: Tractor'), ('CTR031', 'CTR031: Dump Truck'), ('CTR032', 'CTR032: Detachable Dump')], max_length=20, verbose_name='Configuración vehicular'),
        ),
    ]
