# Generated by Django 5.2.4 on 2026-04-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0011_alter_vehicle_vehicle_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='deliveries_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de repartos'),
        ),
    ]
