# Generated by Django 5.2.4 on 2026-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0012_operation_deliveries_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.FileField(blank=True, null=True, upload_to='qrcode', verbose_name='QR')),
                ('digital_cfdi', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sello digital del CFDI')),
                ('sat_stamp', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sello del SAT')),
                ('complement_sat', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cadena original del complemento de certificación digital del SAT')),
                ('sat_certified', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Número de serie del certificado del SAT')),
                ('validation_url', models.CharField(max_length=1000, verbose_name='URL de validacion')),
            ],
        ),
    ]
