# Generated by Django 5.2.4 on 2026-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0013_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='accessories',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Maniobras'),
        ),
    ]
