# Generated by Django 5.2.4 on 2026-06-02 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0014_operation_accessories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to='operations/evidence/%Y/%m/', verbose_name='Archivo de evidencia')),
                ('file_kind', models.CharField(choices=[('PHOTO', 'Foto'), ('PDF', 'PDF')], max_length=10, verbose_name='Tipo de archivo')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='operations_panel.operation', verbose_name='Operación')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_operation_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Evidencia de Operación',
                'verbose_name_plural': 'Evidencias de Operación',
            },
        ),
    ]
