# Generated by Django 5.2.4 on 2026-06-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0015_operationevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_inverse_logistic',
            field=models.BooleanField(blank=True, default=False, verbose_name='¿Es logistica inversa?'),
        ),
    ]
