# Generated by Django 5.2.4 on 2026-07-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0016_operation_is_inverse_logistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='clave_seguimiento',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Clave de seguimiento de cliente'),
        ),
    ]
