# Generated by Django 5.2.4 on 2026-07-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0017_operation_clave_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='clave_seguimiento',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Clave cliente'),
        ),
    ]
