# Generated by Django 5.2.4 on 2026-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0018_alter_operation_clave_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='codigo_plantilla',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Codigo de plantilla'),
        ),
    ]
