# Generated by Django 5.2.4 on 2026-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0020_operation_vehicle_type_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionpacking',
            name='bolsas_ab',
            field=models.IntegerField(default=0, verbose_name='Bolsas de abarrotes'),
        ),
        migrations.AddField(
            model_name='distributionpacking',
            name='bolsas_cvz',
            field=models.IntegerField(default=0, verbose_name='Bolsas de cerveza'),
        ),
        migrations.AddField(
            model_name='distributionpacking',
            name='cajas_ab',
            field=models.IntegerField(default=0, verbose_name='Cajas de abarrotes'),
        ),
        migrations.AddField(
            model_name='distributionpacking',
            name='cajas_cvz',
            field=models.IntegerField(default=0, verbose_name='Cajas de cerveza'),
        ),
        migrations.AddField(
            model_name='distributionpacking',
            name='weight_ab',
            field=models.FloatField(default=0, verbose_name='Peso en Kg de abarrotes'),
        ),
        migrations.AddField(
            model_name='distributionpacking',
            name='weight_cvz',
            field=models.FloatField(default=0, verbose_name='Peso en Kg de cerveza'),
        ),
    ]
