# Generated by Django 5.2.4 on 2026-09-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_panel', '0021_distributionpacking_bolsas_ab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionpacking',
            name='weight_ab',
        ),
        migrations.RemoveField(
            model_name='distributionpacking',
            name='weight_cvz',
        ),
        migrations.AddField(
            model_name='distributionpacking',
            name='weight_ab_bolsas',
            field=models.FloatField(default=0, verbose_name='Peso en Kg de bolsas de abarrotes'),
        ),
        migrations.AddField(
            model_name='distributionpacking',
            name='weight_ab_cajas',
            field=models.FloatField(default=0, verbose_name='Peso en Kg de cajas de abarrotes'),
        ),
        migrations.AddField(
            model_name='distributionpacking',
            name='weight_cvz_bolsas',
            field=models.FloatField(default=0, verbose_name='Peso en Kg de bolsas de cerveza'),
        ),
        migrations.AddField(
            model_name='distributionpacking',
            name='weight_cvz_cajas',
            field=models.FloatField(default=0, verbose_name='Peso en Kg de cajas de cerveza'),
        ),
    ]
