# Generated by Django 5.2.4 on 2026-07-14 16:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations_panel', '0018_alter_operation_clave_seguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationMasterControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('missing_approval', models.BooleanField(default=False, verbose_name='Falta de Vo.Bo.')),
                ('counter_receipt', models.CharField(blank=True, default='', max_length=150, verbose_name='Contrarrecibo')),
                ('counter_receipt_date', models.DateField(blank=True, null=True, verbose_name='Fecha de contrarrecibo')),
                ('customer_invoice_code', models.CharField(blank=True, default='', help_text='Permite registrar uno o varios códigos de factura.', max_length=500, verbose_name='Código de factura')),
                ('customer_invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha de factura del cliente')),
                ('expected_collection_date', models.DateField(blank=True, null=True, verbose_name='Fecha programada de cobro')),
                ('supplier_invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha de factura del proveedor')),
                ('supplier_invoice_number', models.CharField(blank=True, default='', max_length=250, verbose_name='Número de factura del proveedor')),
                ('scheduled_supplier_payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha programada de pago')),
                ('purchase_order', models.CharField(blank=True, default='', max_length=250, verbose_name='Orden de compra')),
                ('sale_amount_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si está vacío, se utilizará el precio de la operación.', max_digits=14, null=True, verbose_name='Precio manual')),
                ('cost_amount_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si está vacío, se utilizará el costo de la operación.', max_digits=14, null=True, verbose_name='Costo manual')),
                ('has_factoring', models.BooleanField(default=False, verbose_name='Tiene factoraje')),
                ('factoring_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto de factoraje')),
                ('factoring_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='Porcentaje de factoraje')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Revisado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_master_controls_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='master_control', to='operations_panel.operation', verbose_name='Operación')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_master_controls_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Control maestro de operación',
                'verbose_name_plural': 'Controles maestros de operaciones',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['missing_approval'], name='operation_c_missing_380eaa_idx'), models.Index(fields=['expected_collection_date'], name='operation_c_expecte_76e543_idx'), models.Index(fields=['scheduled_supplier_payment_date'], name='operation_c_schedul_10a34f_idx'), models.Index(fields=['has_factoring'], name='operation_c_has_fac_7c58f6_idx'), models.Index(fields=['is_reviewed'], name='operation_c_is_revi_893395_idx')],
            },
        ),
    ]
