# Generated by Django 5.2.4 on 2026-07-14 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationControlChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='operation_control.operationmastercontrol', verbose_name='Control maestro')),
            ],
            options={
                'verbose_name': 'Cambio en control maestro',
                'verbose_name_plural': 'Cambios en control maestro',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
