# Generated by Django 5.2.4 on 2026-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_control', '0002_operationcontrolchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmastercontrol',
            name='counter_receipt',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Codigo de plantilla'),
        ),
    ]
