# Generated by Django 5.2.4 on 2026-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_control', '0003_alter_operationmastercontrol_counter_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmastercontrol',
            name='collected_amount_reported',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto efectivamente cobrado al cliente (captura manual).', max_digits=14, null=True, verbose_name='Ingreso real reportado'),
        ),
        migrations.AddField(
            model_name='operationmastercontrol',
            name='supplier_paid_amount_reported',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto efectivamente pagado al proveedor (captura manual).', max_digits=14, null=True, verbose_name='Egreso real reportado'),
        ),
    ]
