# Generated by Django 5.2.4 on 2026-10-05 13:37

import core.finance_panel.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations_panel', '0022_remove_distributionpacking_weight_ab_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFinanceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Categoría')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría de ingreso/egreso externo',
                'verbose_name_plural': 'Categorías de ingresos/egresos externos',
            },
        ),
        migrations.CreateModel(
            name='ExternalFinanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('concept', models.CharField(max_length=255, verbose_name='Concepto')),
                ('entry_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso')], max_length=7, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (IVA incluido)')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to=core.finance_panel.models.external_upload_to, verbose_name='Factura PDF')),
                ('invoice_xml', models.FileField(blank=True, null=True, upload_to=core.finance_panel.models.external_upload_to, verbose_name='Factura XML')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_panel.externalfinancecategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_panel.operation', verbose_name='Operación (opcional)')),
            ],
            options={
                'verbose_name': 'Ingreso/Egreso externo',
                'verbose_name_plural': 'Ingresos/Egresos externos',
                'indexes': [models.Index(fields=['date'], name='finance_pan_date_af4772_idx'), models.Index(fields=['entry_type'], name='finance_pan_entry_t_77ecef_idx'), models.Index(fields=['paid'], name='finance_pan_paid_41d229_idx')],
            },
        ),
    ]
