# Generated by Django 5.2.4 on 2026-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfinanceentry',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha limite para pago'),
        ),
        migrations.AlterField(
            model_name='externalfinanceentry',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pagado'),
        ),
    ]
