# Generated by Django 5.2.4 on 2026-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_panel', '0002_alter_externalfinanceentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfinanceentry',
            name='paid',
            field=models.BooleanField(blank=True, default=False, verbose_name='Pagado'),
        ),
    ]
