# Generated by Django 5.2.4 on 2025-09-02 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(verbose_name='Token Expiry')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Google Drive Credential',
                'verbose_name_plural': 'Google Drive Credentials',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('drive_id', models.CharField(max_length=255, verbose_name='Google Drive ID')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME Type')),
                ('size', models.BigIntegerField(default=0, verbose_name='Size in bytes')),
                ('md5_checksum', models.CharField(blank=True, max_length=32, verbose_name='MD5 Checksum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Google Drive File',
                'verbose_name_plural': 'Google Drive Files',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Folder Name')),
                ('drive_id', models.CharField(max_length=255, verbose_name='Google Drive ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Google Drive Folder',
                'verbose_name_plural': 'Google Drive Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveServiceAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('credentials_json', models.TextField(verbose_name='Service Account Credentials JSON')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Google Drive Service Account',
                'verbose_name_plural': 'Google Drive Service Accounts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
