# Generated by Django 5.2.4 on 2025-09-02 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_drive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivecredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_credential', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googledrivefile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googledrivefolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfolders', to='google_drive.googledrivefolder'),
        ),
        migrations.AddField(
            model_name='googledrivefolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googledrivefile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='google_drive.googledrivefolder'),
        ),
        migrations.AlterUniqueTogether(
            name='googledrivefolder',
            unique_together={('user', 'drive_id')},
        ),
        migrations.AlterUniqueTogether(
            name='googledrivefile',
            unique_together={('user', 'drive_id')},
        ),
    ]
