# Generated by Django 5.2.4 on 2025-10-26 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_drive', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrivefile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='googledrivefolder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
