# Generated by Django 5.2.4 on 2025-10-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='system',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('SYSTEM', 'SYSTEM'), ('ADMINISTRACION', 'ADMINISTRACION'), ('OPERACIONES', 'OPERACIONES'), ('COMERCIAL', 'COMERCIAL'), ('SALE', 'VENTAS'), ('RH', 'RH'), ('ATTENDANCE', 'ATTENDANCE')], default='NONE', max_length=150, null=True, verbose_name='Sistema'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='system',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('SYSTEM', 'SYSTEM'), ('ADMINISTRACION', 'ADMINISTRACION'), ('OPERACIONES', 'OPERACIONES'), ('COMERCIAL', 'COMERCIAL'), ('SALE', 'VENTAS'), ('RH', 'RH'), ('ATTENDANCE', 'ATTENDANCE')], default='NONE', max_length=150, null=True, verbose_name='Sistema'),
        ),
    ]
