# Generated by Django 5.2.4 on 2025-10-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_category_system_alter_systemuser_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
