# Generated by Django 5.2.4 on 2026-02-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_category_old_id_section_old_id_systemuser_old_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='system',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('SYSTEM', 'SYSTEM'), ('ADMINISTRACION', 'ADMINISTRACION'), ('OPERACIONES', 'OPERACIONES'), ('COMERCIAL', 'COMERCIAL'), ('SALE', 'VENTAS'), ('RH', 'RH'), ('ATTENDANCE', 'ATTENDANCE'), ('SUPPLIER', 'SUPPLIER')], default='NONE', max_length=150, null=True, verbose_name='Sistema'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='system',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('SYSTEM', 'SYSTEM'), ('ADMINISTRACION', 'ADMINISTRACION'), ('OPERACIONES', 'OPERACIONES'), ('COMERCIAL', 'COMERCIAL'), ('SALE', 'VENTAS'), ('RH', 'RH'), ('ATTENDANCE', 'ATTENDANCE'), ('SUPPLIER', 'SUPPLIER')], default='NONE', max_length=150, null=True, verbose_name='Sistema'),
        ),
    ]
