# Generated by Django 5.2.4 on 2026-03-24 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_assistant', '0002_initial'),
        ('telegram_bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatAssistantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_telegram_id', models.BigIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openai_assistant.assistant')),
            ],
        ),
    ]
