# Generated by Django 5.2.4 on 2026-03-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0002_telegramchatassistantrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchatassistantrule',
            name='chat_telegram_id',
        ),
    ]
