# Generated by Django 5.2.4 on 2026-03-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0003_remove_telegramchatassistantrule_chat_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchatassistantrule',
            name='chat_name',
            field=models.CharField(default='123', max_length=255, verbose_name='Chat Name'),
            preserve_default=False,
        ),
    ]
