# Generated by Django 5.2.4 on 2026-03-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0004_telegramchatassistantrule_chat_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramChatAssistantRule',
        ),
    ]
