# Generated by Django 5.2.4 on 2026-03-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_assistant', '0002_initial'),
        ('telegram_bots', '0005_delete_telegramchatassistantrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='default_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_bots_default', to='openai_assistant.assistant'),
        ),
    ]
