# Generated by Django 5.2.4 on 2026-03-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0006_telegrambot_default_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots_chats', to='telegram_bots.telegrambot'),
        ),
    ]
