# Generated by Django 5.2.4 on 2026-03-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0007_telegramchat_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='telegram_id',
            field=models.BigIntegerField(verbose_name='Telegram Chat ID'),
        ),
    ]
