# Generated by Django 5.2.4 on 2026-05-27 07:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations_panel', '0014_operation_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('ENVIADA', 'Enviada'), ('EN_ESPERA', 'En Espera'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='purchase_orders/pdf/', verbose_name='PDF')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='purchase_orders/invoices/', verbose_name='Factura del cliente')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('waiting_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en espera')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='operations_panel.client', verbose_name='Cliente')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='operations_panel.driver', verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderAccessory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('CASETAS', 'Casetas'), ('GASOLINA', 'Gasolina'), ('MANIOBRAS', 'Maniobras'), ('OTROS', 'Otros')], max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('operation', models.ForeignKey(help_text='Operación a la cual está ligado este accesorio', on_delete=django.db.models.deletion.CASCADE, to='operations_panel.operation', verbose_name='Operación relacionada')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='admin_panel.purchaseorder', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations_panel.operation', verbose_name='Operación')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='admin_panel.purchaseorder', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Operación en Orden',
                'verbose_name_plural': 'Operaciones en Orden',
                'unique_together': {('purchase_order', 'operation')},
            },
        ),
    ]
