# Generated by Django 5.2.4 on 2026-05-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('operations_panel', '0014_operation_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='client',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='operations_panel.supplier', verbose_name='Cliente'),
        ),
    ]
