# Generated by Django 5.2.4 on 2026-05-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_purchaseorder_client_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/supplier_invoices/pdf/', verbose_name='Factura del proveedor (PDF)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_invoice_xml',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/supplier_invoices/xml/', verbose_name='Factura del proveedor (XML)'),
        ),
    ]
