# Generated by Django 5.2.4 on 2026-06-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_purchaseorder_supplier_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_invoice_payment_pdf',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/supplier_invoices/pdf/', verbose_name='Complemento de pago (PDF)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_invoice_payment_xml',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/supplier_invoices/xml/', verbose_name='Complemento de pago (XML)'),
        ),
    ]
