# Generated by Django 5.2.4 on 2025-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturapiinvoice',
            name='customer',
            field=models.CharField(choices=[('I', 'I: Factura'), ('E', 'E: Nota de Crédito'), ('P', 'P: Complemento de pago'), ('T', 'T: Translado'), ('N', 'N: Nomina')], default='I', max_length=2, verbose_name='Tipo de comprobante'),
        ),
        migrations.DeleteModel(
            name='FacturapiClient',
        ),
    ]
