# Generated by Django 5.2.4 on 2025-09-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturapi', '0002_alter_facturapiinvoice_customer_and_more'),
        ('operations_panel', '0004_operation_invoices_operation_shipment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturapiinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='operations_panel.client', verbose_name='Cliente'),
        ),
    ]
