# Generated by Django 5.2.4 on 2025-10-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturapi', '0003_alter_facturapiinvoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturapiinvoice',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturapiinvoiceitem',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturapiinvoicepayment',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturapiproduct',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturapitax',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
