# Generated by Django 5.2.4 on 2025-10-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturapi', '0004_facturapiinvoice_old_id_facturapiinvoiceitem_old_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturapiinvoice',
            name='payment_form',
            field=models.CharField(choices=[('PUE', 'PUE'), ('PPD', 'PPD')], default='PPD', max_length=5, null=True, verbose_name='Forma de pago'),
        ),
    ]
