# Generated by Django 5.2.4 on 2025-10-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturapi', '0005_alter_facturapiinvoice_payment_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturapiinvoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Por pagar'),
        ),
    ]
