# Generated by Django 5.2.4 on 2026-02-10 09:38

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre de la solicitud')),
                ('invoice_pdf', models.FileField(upload_to='payment_requests/invoice/pdf/', verbose_name='Factura de ingreso (PDF)')),
                ('invoice_xml', models.FileField(upload_to='payment_requests/invoice/xml/', verbose_name='Factura de ingreso (XML)')),
                ('vehicle_control', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='El control vehicular debe tener 1 letra seguida de 4 números', regex='^[A-Za-z]{1}[0-9]{4}$')], verbose_name='Control vehicular')),
                ('amount_before_taxes', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto previo a impuestos')),
                ('payment_complement_pdf', models.FileField(blank=True, null=True, upload_to='payment_requests/complement/pdf/', verbose_name='Complemento de pago (PDF)')),
                ('payment_complement_xml', models.FileField(blank=True, null=True, upload_to='payment_requests/complement/xml/', verbose_name='Complemento de pago (XML)')),
                ('status', models.CharField(choices=[('revision', 'EN REVISION'), ('aprobada', 'APROBADA'), ('denegada', 'DENEGADA'), ('pagada', 'PAGADA')], default='revision', max_length=20, verbose_name='Estatus')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
