# Generated by Django 5.2.4 on 2026-03-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_panel', '0002_remove_paymentrequest_name_paymentrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('revision', 'EN REVISION'), ('aprobada', 'APROBADA'), ('denegada', 'DENEGADA'), ('complemento', 'EN ESPERA DE COMPLEMENTO'), ('finalizada', 'FINALIZADA')], default='revision', max_length=20, verbose_name='Estatus'),
        ),
    ]
