# Generated by Django 5.2.4 on 2025-09-02 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('telegram_command', models.CharField(max_length=255, verbose_name='Command')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('model', models.CharField(default='gpt-4o', max_length=100, verbose_name='Model')),
                ('openai_id', models.CharField(blank=True, max_length=255, verbose_name='OpenAI Assistant ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Assistant',
                'verbose_name_plural': 'Assistants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('openai_thread_id', models.CharField(blank=True, max_length=255, verbose_name='OpenAI Thread ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20, verbose_name='Role')),
                ('content', models.TextField(verbose_name='Content')),
                ('openai_message_id', models.CharField(blank=True, max_length=255, verbose_name='OpenAI Message ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('function', 'Function'), ('retrieval', 'Retrieval'), ('code_interpreter', 'Code Interpreter')], max_length=50, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['assistant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=255, verbose_name='Tool Name')),
                ('input_data', models.JSONField(default=dict, verbose_name='Input Data')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='Output Data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('openai_tool_call_id', models.CharField(blank=True, max_length=255, verbose_name='OpenAI Tool Call ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Tool Execution',
                'verbose_name_plural': 'Tool Executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
